export const THEMES = [
  {
    id: "midnight",
    name: "Midnight",
    bg: "#0D1117",
    text: "#F0EDE8",
    accent: "#FF4D5A",
    cardBg: "#161B22",
    font: "serif",
  },
  {
    id: "paper",
    name: "Paper",
    bg: "#F5F0E8",
    text: "#1A1A1A",
    accent: "#3563E9",
    cardBg: "#FFFFFF",
    font: "sans",
  },
  {
    id: "forest",
    name: "Forest",
    bg: "#1A2B1A",
    text: "#D4F0C0",
    accent: "#5FD068",
    cardBg: "#1F331F",
    font: "sans",
  },
  {
    id: "cream",
    name: "Cream",
    bg: "#2D1B0E",
    text: "#FAE8C8",
    accent: "#E8A838",
    cardBg: "#3A2415",
    font: "serif",
  },
  {
    id: "ocean",
    name: "Ocean",
    bg: "#0A1628",
    text: "#E8F4FC",
    accent: "#22D3EE",
    cardBg: "#0F2035",
    font: "sans",
  },
  {
    id: "rose",
    name: "Rose",
    bg: "#FFF0F3",
    text: "#2D1020",
    accent: "#E11D74",
    cardBg: "#FFFFFF",
    font: "serif",
  },
  {
    id: "slate",
    name: "Slate",
    bg: "#1E293B",
    text: "#F1F5F9",
    accent: "#3B82F6",
    cardBg: "#334155",
    font: "sans",
  },
  {
    id: "lemon",
    name: "Lemon",
    bg: "#FEFCE8",
    text: "#1C1917",
    accent: "#EA580C",
    cardBg: "#FFFFFF",
    font: "sans",
  },
  {
    id: "mono",
    name: "Mono",
    bg: "#000000",
    text: "#FFFFFF",
    accent: "#FFFFFF",
    cardBg: "#1A1A1A",
    font: "sans",
  },
];

export function getThemeById(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}
